<Project>
  <Name>builder</Name>
  <ProjectItem type="NClass.DiagramEditor.ClassDiagram.Diagram" assembly="NClass.DiagramEditor, Version=2.4.1823.0, Culture=neutral, PublicKeyToken=null">
    <Name>builderpattern</Name>
    <Language>CSharp</Language>
    <Entities>
      <Entity type="Class">
        <Name>Client</Name>
        <Access>Public</Access>
        <Location left="266" top="29" />
        <Size width="162" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>Director</Name>
        <Access>Public</Access>
        <Location left="17" top="188" />
        <Size width="162" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public Product Construct()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>IBuilder</Name>
        <Access>Public</Access>
        <Location left="462" top="148" />
        <Size width="162" height="111" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public void BuildPart()</Member>
        <Member type="Method">public Product GetResult()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>Product</Name>
        <Access>Public</Access>
        <Location left="462" top="464" />
        <Size width="162" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Field">List parts</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>Builder</Name>
        <Access>Public</Access>
        <Location left="462" top="308" />
        <Size width="162" height="111" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public void BuildPart()</Member>
        <Member type="Method">public Product GetResult()</Member>
        <Modifier>None</Modifier>
      </Entity>
    </Entities>
    <Relationships>
      <Relationship type="Association" first="0" second="1">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>300</X>
          <Y>133</Y>
        </BendPoint>
        <Direction>Unidirectional</Direction>
        <AssociationType>Aggregation</AssociationType>
      </Relationship>
      <Relationship type="Association" first="0" second="2">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>384</X>
          <Y>133</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>437</X>
          <Y>176</Y>
        </BendPoint>
        <Direction>Unidirectional</Direction>
        <AssociationType>Aggregation</AssociationType>
      </Relationship>
      <Relationship type="Association" first="1" second="2">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>204</X>
          <Y>274</Y>
        </BendPoint>
        <Direction>Unidirectional</Direction>
        <AssociationType>Aggregation</AssociationType>
      </Relationship>
      <Relationship type="Dependency" first="4" second="2">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
      </Relationship>
      <Relationship type="Association" first="4" second="3">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <Direction>Unidirectional</Direction>
        <AssociationType>Aggregation</AssociationType>
      </Relationship>
    </Relationships>
  </ProjectItem>
</Project>